# Generated by Django 4.0.4 on 2022-04-27 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='post'),
            preserve_default=False,
        ),
    ]
