# Generated by Django 4.0.4 on 2022-04-29 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=25)),
                ('job_title', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=300)),
                ('website', models.URLField()),
                ('message', models.TextField(help_text='How can we help of service to you?')),
            ],
        ),
    ]
