# Generated by Django 4.0.4 on 2022-04-29 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_consultation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Consultation',
        ),
    ]
