# Generated by Django 4.0.4 on 2022-04-30 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_consultation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name_plural': 'Services'},
        ),
    ]
