# Generated by Django 4.0.4 on 2022-05-02 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_alter_services_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='link',
            field=models.URLField(default='https://www.gogle.com/'),
            preserve_default=False,
        ),
    ]
