# Generated by Django 4.0.4 on 2022-05-23 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_alter_consultation_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='staff_images')),
            ],
        ),
    ]
